# Generated by Django 2.1.7 on 2019-04-23 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('cod_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('cod_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
        ),
    ]
