# Generated by Django 2.1.7 on 2019-04-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='estado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
