# Generated by Django 2.1.7 on 2019-04-23 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_notificacion_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='estado',
        ),
    ]
